
import React from 'react';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import '../styles/styles.css';

const inter = Inter({ subsets: ['latin'] });

const Layout = ({ children }) => {
  return (
    <>
      <Head>
      
        <title> website builder by himanshu verma</title>
        <meta name="description" content="Generated by create next app" />
      
        <link rel="stylesheet" href={inter.href} />
      </Head>
      <body className={inter.className}>{children}</body>
    </>
  );
};

export default Layout;
